#!/bin/bash
ALPINE_VERSION=3.14.1
MIRRORS_URL=https://mirrors.ustc.edu.cn
BASE_URL=$MIRRORS_URL/alpine/latest-stable/releases/x86_64/alpine-minirootfs-$ALPINE_VERSION-x86_64.tar.gz
TAR_NAME=rootfs.alpine.tar.gz

download(){
    echo 'step: release_tar..'
    if [ ! -d rootfs ];then
        mkdir rootfs
    fi
    rm -rf rootfs/*
    if [ ! -s *.tar.gz ];then
        wget $BASE_URL 
    fi
    tar -zxpf *.tar.gz -C rootfs
}

prepare(){
    echo 'step: pre_build..'
    cp -rf data/* rootfs/tmp/
    cp -f /etc/resolv.conf rootfs/etc/resolv.conf
}

build(){
    echo 'step: build_rootfs..'
    cp chroot rootfs/chroot
    chmod +x rootfs/chroot
    chroot rootfs /bin/ash -c "sh chroot"
    rm rootfs/chroot
}

package(){
    echo 'step: package_rootfs..'
    if [ ! -d tars ];then
        mkdir tars
    fi
    cd rootfs;
    tar -zcpf ../tars/$TAR_NAME `ls`
    cd ..;
    chown `id -un` tars/$TAR_NAME
}

clear(){
    echo 'step: clear..'
    rm -rf rootfs
    rm *.tar.gz
}

# 构建基础rootfs
download
prepare
build
package
clear