#!/bin/bash
set -ex

readonly DOCKER_VER='20.10.8'

readonly PACKAGES_NAMES='
    curl openssl openssh-client iptables xz libstdc++ git
'
readonly UNNECESSARY_DIRS='
	/home /media/cdrom /media/floppy /media/usb /mnt /srv /usr/local/bin
	/usr/local/lib /usr/local/share
'

einfo() {
    printf '\n\033[1;31m> %s\033[0m\n' "$@" >&2  # bold red
}

upgrade(){
    einfo 'chroot: upgrade..'
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
    apk --no-cache --update-cache upgrade --update
}

packages(){
    einfo 'chroot: install packages..'
    apk add --no-cache --update-cache $PACKAGES_NAMES
}

timezone() {
    einfo 'chroot: install timezone..'
	local timezone="Asia/Shanghai"
    apk add --no-cache --update-cache tzdata
	install -D /usr/share/zoneinfo/$timezone /etc/zoneinfo/$timezone
	ln -sf /etc/zoneinfo/$timezone /etc/localtime
	apk del tzdata
}

passwd(){
    einfo 'chroot: install passwd..'
    sed -i '1d' /etc/passwd;sed -i '1i\root:x:0:0:root:/:/bin/ash' /etc/passwd
}

docker(){
    einfo 'chroot: install docker..'
    chmod 775 /usr/local/sbin/docker.sh
    chmod 775 /usr/local/sbin/generate-tls-key.sh
    mkdir -p /root
    mkdir -p /var/lib/wsl2-docker
    mkdir -p /usr/local/bin
    curl -fLo docker.tgz "http://mirrors.ustc.edu.cn/docker-ce/linux/static/stable/x86_64/docker-${DOCKER_VER}.tgz"
    tar xzf docker.tgz
    mv docker/* /usr/local/bin/
    rm -rf docker
    rm docker.tgz
    addgroup -S docker
    mkdir -p /etc/docker
    tee /etc/docker/daemon.json <<-'EOF'
{
"registry-mirrors": [
"http://hub-mirror.c.163.com",
"https://docker.mirrors.ustc.edu.cn",
"https://registry.docker-cn.com"
]
}
EOF
}

clear(){
    einfo 'chroot: clear up..'
    echo -e "# " -> /etc/resolv.conf
    rm -Rf /dev/*
    rm -Rf /tmp/*
    if [ -f /sbin/apk ]; then
        rm -Rf /var/cache/apk/*
    else
        rm -Rf /etc/apk /lib/apk /var/cache/apk
    fi
    for dir in $UNNECESSARY_DIRS; do
        rmdir -p "$dir" 2>/dev/null || true
    done
}

upgrade
packages
timezone
passwd
docker
clear