#!/bin/bash
upgrade(){
    echo '██████████ step: chroot upgrade..'
#         cat>/etc/apk/repositories<<EOF
# http://mirrors.ustc.edu.cn/alpine/edge/main
# http://mirrors.ustc.edu.cn/alpine/edge/community
# http://mirrors.ustc.edu.cn/alpine/edge/testing
# EOF
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
    apk --no-cache upgrade --update 
}

library(){
    echo '██████████ step: chroot install_lib..'
    apk --no-cache add git bash libstdc++
    echo '██████████ step: chroot zsh..'
    apk --no-cache add zsh
    wget -P /root/ https://gitee.com/mirrors/oh-my-zsh/raw/master/tools/install.sh
    chmod +x /root/install.sh
    REMOTE=https://gitee.com/mirrors/oh-my-zsh.git RUNZSH=no sh /root/install.sh --unattended
    git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    cp -f /tmp/zsh/.zshrc /root/.zshrc
    tar -zxpf /tmp/zsh/plugins.tar.gz -C root/.oh-my-zsh/custom/plugins
    rm -rf /root/install.sh
}

docker(){
    apk add --no-cache docker docker-compose openrc lxc musl-dev
    openrc
    mkdir -p /run/openrc/
    touch /run/openrc/softlevel
    echo -e 'openrc && mkdir -p /run/openrc/ && touch /run/openrc/softlevel && service docker start' > /etc/profile.d/docker-start.sh
    tee /etc/docker/daemon.json <<-'EOF'
{
"registry-mirrors": [
"http://hub-mirror.c.163.com",
"https://docker.mirrors.ustc.edu.cn",
"https://registry.docker-cn.com"
]
}
EOF
    sed -ie 's@${DOCKER_OPTS}@-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 -p \\"${pidfile}\\" ${DOCKER_OPTS}@' /etc/init.d/docker
}

podman(){
    echo '██████████ step: chroot install_podman..'
    apk --no-cache add podman
    cp /etc/containers/registries.conf /etc/containers/registries.conf.bak
    cat>/etc/containers/registries.conf<<EOF
unqualified-search-registries = ['docker.io']

[[registry]]
prefix = "docker.io"
location = "hub-mirror.c.163.com"

[[registry.mirror]]
prefix = "docker.io"
location = "05l46sac.mirror.aliyuncs.com"
EOF
}

setup(){
    echo '██████████ step: chroot setup..'
    cp -f /tmp/profile /etc/profile
    sed -i '1d' /etc/passwd;sed -i '1i\root:x:0:0:root:/root:/bin/zsh' /etc/passwd
}

clear(){
    echo -e "# " -> /etc/resolv.conf
    rm -rf /tmp/*
    rm -rf `find /var/cache/apk/ -type f`
}

upgrade
library
docker
setup
clear