#!/bin/bash
set -ex

readonly DOCKER_VER='20.10.8'

# 网易
readonly MIRROR='mirrors.163.com'
# 清华
# readonly MIRROR='mirrors.ustc.edu.cn'
# 阿里
# readonly MIRROR='mirrors.aliyun.com'


readonly UNNECESSARY_DIRS='
	/home /media/cdrom /media/floppy /media/usb /mnt /srv /usr/local/bin
	/usr/local/lib /usr/local/share
'
einfo() {
    printf '\n\033[1;31m> %s\033[0m\n' "$@" >&2  # bold red
}

upgrade(){
    einfo 'chroot: upgrade..'
    sed -i.bak \
    -e 's|^mirrorlist=|#mirrorlist=|' \
    -e 's|^#baseurl=|baseurl=|' \
    -e 's|http://mirror.centos.org|https://'$MIRROR'|' \
    /etc/yum.repos.d/CentOS-*.repo
}

packages(){
    einfo 'chroot: install packages..'
    mknod -m 666 /dev/random c 1 8
    mknod -m 666 /dev/urandom c 1 9
    yum install iptables -y
}


timezone() {
    einfo 'chroot: install timezone..'
	local timezone="Asia/Shanghai"
	install -D /usr/share/zoneinfo/$timezone /etc/zoneinfo/$timezone
	ln -sf /etc/zoneinfo/$timezone /etc/localtime
}

passwd(){
    einfo 'chroot: install passwd..'
    sed -i '1d' /etc/passwd;sed -i '1i\root:x:0:0:root:/:/bin/bash' /etc/passwd
}

docker(){
    einfo 'chroot: install docker..'
    chmod 775 /usr/local/sbin/docker.sh
    chmod 775 /usr/local/sbin/generate-tls-key.sh
    mkdir -p /root
    mkdir -p /var/lib/wsl2-docker
    mkdir -p /usr/local/bin
    curl -fLo docker.tgz "https://$MIRROR/docker-ce/linux/static/stable/x86_64/docker-${DOCKER_VER}.tgz"
    tar xzf docker.tgz
    mv docker/* /usr/local/bin/
    rm -rf docker
    rm docker.tgz
    mkdir -p /etc/docker
    tee /etc/docker/daemon.json <<-'EOF'
{
"registry-mirrors": [
"http://hub-mirror.c.163.com",
"https://docker.mirrors.ustc.edu.cn",
"https://registry.docker-cn.com"
]
}
EOF
}

clear(){
    einfo 'chroot: clear up..'
    yum clean all
    rm -Rf /dev/*
    rm -Rf /tmp/*
    rm -Rf /*.log
    echo -e "# " -> /etc/resolv.conf
    for dir in $UNNECESSARY_DIRS; do
        rmdir -p "$dir" 2>/dev/null || true
    done
}

upgrade
packages
timezone
passwd
docker
clear