#!/bin/bash
set -ex

einfo() {
	printf '\n\033[1;36m> %s\033[0m\n' "$@" >&2  # bold cyan
}

alpine(){
    einfo 'Make alpine...'
    cd alpine
    sh build
    cd ..
}

centos(){
    einfo 'Make centos...'
    cd centos
    sh build
    cd ..
}

ubuntu(){
    einfo 'Make ubuntu...'
    cd ubuntu
    sh build
    cd ..
}

artifacts(){
    mkdir -p artifacts
    cp -rf alpine/tars/* artifacts/
    cp -rf centos/tars/* artifacts/
    cp -rf ubuntu/tars/* artifacts/
}


alpine
centos
ubuntu
artifacts