name: Releases
on:
  # 手动触发事件
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: build
      run: sudo sh build_all