name: GitHub Releases
on:
  # 手动触发事件
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: CurrentDate
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: checkout 
      uses: actions/checkout@v2
    - name: build
      run: sudo sh build_all
    - name: release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.PRIVATE_TOKEN }}"
        automatic_release_tag: "latest"
        title: ${{ steps.date.outputs.date }}
        prerelease: false
        files: |
          artifacts/*